# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New section
"""

import pandas as pd
import numpy as np

df = pd.read_csv("spotify_songs_dataset.csv")

df.info()

df['release_date'] = pd.to_datetime(df['release_date'], format='%Y-%m-%d', errors='coerce')
print(df)
print(df.dtypes)

# Convert the column to datetime and remove the time part
#df['release_date'] = pd.to_datetime(df['release_date']).dt.date

df['release_date'] = df['release_date'].dt.normalize()
print(df)
print(df.dtypes)

df.describe()

df['duration'] = df['duration'].fillna(df['duration'].mean())

df['language'] = df['language'].fillna(df['language'].mode()[0])

df = df.drop('collaboration', axis=1)

df.describe()

df.info()

cols_to_clean = ['song_id', 'song_title', 'artist', 'album','genre', 'language', 'explicit_content', 'label', 'composer', 'producer' ]

# Remove special characters from selected columns

for col in cols_to_clean:
    df[col] = df[col].str.replace(r'[^A-Za-z0-9- ]+', '', regex=True)


print(df).head()

df.info()

df.to_excel('cleaned_dataset.xlsx', index=False)

